import express from 'express';
import Product from '../models/Product.js';
import Order from '../models/Order.js';

const router = express.Router();

// GET /api/merchant/stats - Aggregated seller statistics (scoped to merchant if merchantId provided)
router.get('/stats', async (req, res) => {
  try {
    const { merchantId } = req.query;
    const productQuery = merchantId ? { merchantId } : {};

    const merchantProducts = await Product.find(productQuery).select('_id price');
    const totalProducts = merchantProducts.length;

    if (totalProducts === 0) {
      return res.json({
        success: true,
        stats: {
          totalRevenue: 0,
          totalOrders: 0,
          completedOrders: 0,
          totalProducts: 0,
          abandonedCount: 0,
          recoveredCount: 0,
          recoveredRevenue: 0,
          recoveryRate: 0
        }
      });
    }

    const productIds = merchantProducts.map(p => p._id);
    const orderQuery = { 'items.product': { $in: productIds } };
    const allOrders = await Order.find(orderQuery);

    const totalOrdersCount = allOrders.length;
    const completedOrders = allOrders.filter(o => o.paymentStatus === 'paid');

    // Calculate revenue generated by this merchant's products specifically
    const totalRevenue = completedOrders.reduce((sum, order) => {
      const merchantItems = order.items.filter(item =>
        productIds.some(pid => pid.toString() === item.product?.toString())
      );
      const itemsSum = merchantItems.reduce((iSum, item) => iSum + (item.price * item.quantity), 0);
      return sum + itemsSum;
    }, 0);

    const abandonedOrders = allOrders.filter(o => o.checkoutStatus === 'abandoned');
    const recoveredOrders = allOrders.filter(o => o.checkoutStatus === 'recovered');
    
    const recoveredRevenue = recoveredOrders.reduce((sum, order) => {
      const merchantItems = order.items.filter(item =>
        productIds.some(pid => pid.toString() === item.product?.toString())
      );
      return sum + merchantItems.reduce((iSum, item) => iSum + (item.price * item.quantity), 0);
    }, 0);

    const recoveryRate = abandonedOrders.length + recoveredOrders.length > 0
      ? Math.round((recoveredOrders.length / (abandonedOrders.length + recoveredOrders.length)) * 100)
      : 0;

    res.json({
      success: true,
      stats: {
        totalRevenue,
        totalOrders: totalOrdersCount,
        completedOrders: completedOrders.length,
        totalProducts,
        abandonedCount: abandonedOrders.length,
        recoveredCount: recoveredOrders.length,
        recoveredRevenue,
        recoveryRate
      }
    });
  } catch (error) {
    console.error('Error fetching merchant stats:', error);
    res.status(500).json({ success: false, message: 'Error fetching merchant statistics', error: error.message });
  }
});

// GET /api/merchant/products - Get products belonging to a specific merchant
router.get('/products', async (req, res) => {
  try {
    const { merchantId, search, category, page = 1, limit = 50 } = req.query;
    const query = {};

    if (merchantId) {
      query.merchantId = merchantId;
    }

    if (category) {
      query.category = category;
    }

    if (search) {
      query.$or = [
        { title: { $regex: search, $options: 'i' } },
        { brand: { $regex: search, $options: 'i' } },
        { category: { $regex: search, $options: 'i' } }
      ];
    }

    const skip = (Number(page) - 1) * Number(limit);
    const total = await Product.countDocuments(query);
    const products = await Product.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit));

    res.json({
      success: true,
      total,
      products
    });
  } catch (error) {
    console.error('Error fetching merchant products:', error);
    res.status(500).json({ success: false, message: 'Error fetching merchant products', error: error.message });
  }
});

// GET /api/merchant/orders - Get orders containing this merchant's products
router.get('/orders', async (req, res) => {
  try {
    const { merchantId, status, search } = req.query;
    let query = {};

    if (merchantId) {
      const merchantProducts = await Product.find({ merchantId }).select('_id');
      const productIds = merchantProducts.map(p => p._id);
      
      if (productIds.length === 0) {
        return res.json({ success: true, count: 0, orders: [] });
      }

      query['items.product'] = { $in: productIds };
    }

    if (status && status !== 'all') {
      query.paymentStatus = status;
    }

    if (search) {
      query.$or = [
        { orderId: { $regex: search, $options: 'i' } },
        { 'customerDetails.name': { $regex: search, $options: 'i' } },
        { 'customerDetails.email': { $regex: search, $options: 'i' } }
      ];
    }

    const orders = await Order.find(query)
      .populate('items.product')
      .sort({ createdAt: -1 });

    res.json({ success: true, count: orders.length, orders });
  } catch (error) {
    console.error('Error fetching merchant orders:', error);
    res.status(500).json({ success: false, message: 'Error fetching merchant orders', error: error.message });
  }
});

// PUT /api/merchant/orders/:id/status - Update order fulfillment or payment status
router.put('/orders/:id/status', async (req, res) => {
  try {
    const { id } = req.params;
    const { paymentStatus, checkoutStatus } = req.body;

    const order = await Order.findOne({ $or: [{ _id: id }, { orderId: id }] });
    if (!order) {
      return res.status(404).json({ success: false, message: 'Order not found' });
    }

    if (paymentStatus) order.paymentStatus = paymentStatus;
    if (checkoutStatus) order.checkoutStatus = checkoutStatus;

    await order.save();
    res.json({ success: true, message: 'Order status updated', order });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error updating order status', error: error.message });
  }
});

// POST /api/merchant/products - Add a new product to store linked to this merchant
router.post('/products', async (req, res) => {
  try {
    const {
      merchantId,
      merchantEmail,
      merchantName,
      merchantStoreName,
      title,
      brand,
      category,
      price,
      originalPrice,
      shortDescription,
      description,
      thumbnail,
      images,
      specs,
      highlights,
      badge,
      isFeatured = false,
      isDeal = false
    } = req.body;

    if (!title || !brand || !category || !price || !thumbnail) {
      return res.status(400).json({ success: false, message: 'Please provide all required product fields' });
    }

    const baseSlug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    const slug = `${baseSlug}-${Date.now().toString().slice(-4)}`;

    const numPrice = Number(price);
    const numOrig = originalPrice ? Number(originalPrice) : numPrice;
    const discountPercent = numOrig > numPrice ? Math.round(((numOrig - numPrice) / numOrig) * 100) : 0;

    const product = new Product({
      merchantId: merchantId || 'seed_merchant_nexvolt',
      merchantEmail: merchantEmail || '',
      merchantName: merchantName || 'NexVolt Official Partner',
      merchantStoreName: merchantStoreName || '',
      title,
      slug,
      brand,
      category,
      price: numPrice,
      originalPrice: numOrig,
      discountPercent,
      rating: 4.8,
      numReviews: 1,
      badge: badge || '',
      isFeatured: Boolean(isFeatured),
      isDeal: Boolean(isDeal),
      shortDescription: shortDescription || title,
      description: description || shortDescription || title,
      thumbnail,
      images: images && images.length ? images : [thumbnail],
      specs: Array.isArray(specs) ? specs : [],
      highlights: Array.isArray(highlights) ? highlights : []
    });

    await product.save();
    res.status(201).json({ success: true, message: 'Product published successfully', product });
  } catch (error) {
    console.error('Error creating product:', error);
    res.status(500).json({ success: false, message: 'Error publishing product', error: error.message });
  }
});

// PUT /api/merchant/products/:id - Update product details
router.put('/products/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const updates = req.body;

    if (updates.price && updates.originalPrice) {
      const p = Number(updates.price);
      const o = Number(updates.originalPrice);
      updates.discountPercent = o > p ? Math.round(((o - p) / o) * 100) : 0;
    }

    const product = await Product.findByIdAndUpdate(id, updates, { new: true });
    if (!product) {
      return res.status(404).json({ success: false, message: 'Product not found' });
    }

    res.json({ success: true, message: 'Product updated', product });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error updating product', error: error.message });
  }
});

// DELETE /api/merchant/products/:id - Delete product from catalog
router.delete('/products/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const product = await Product.findByIdAndDelete(id);
    if (!product) {
      return res.status(404).json({ success: false, message: 'Product not found' });
    }

    res.json({ success: true, message: 'Product deleted from store catalog' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Error deleting product', error: error.message });
  }
});

export default router;
